### ISSUE TITLE
Publish to crates.io Plz

### ISSUE THREAD

**Issue by IGBC** [albel727/rust-ghostscript#1]
I wanna use this, can you please publish it.

**Comment by rawnly** [comment]
If anyone is wondering 

```toml
[dependencies]
ghostscript = { git = "https://github.com/abel727/rust-ghostscript" }

```
